'use strict';
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

/**
 * car model file
 * autogenerated by mongoose-scaffold-crud
 */

var carsSchema = new Schema({
    color: 'String',
    model: 'String'
});

module.exports = mongoose.model('cars', carsSchema);